name: ghost_restart
description: 'A short script using appleboy''s SSH to restart Ghost apps (ghost.org).'

on:
  push:
    branches:
      - main

jobs:
    
  build:

    runs-on: ubuntu-20.04
      
    steps:
    - name: pull to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SUDO_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PATH_TO_GHOST }}/..
          echo ${{ secrets.SUDO_PASSWORD }} | ${{ secrets.GIT_PULL_SCRIPT }}
          
    - name: ssh and restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SUDO_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd ${{ secrets.PATH_TO_GHOST }} && echo ${{ secrets.SUDO_PASSWORD }} | sudo -S ghost restart
